<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nettemplate"
 *
 * Auto generated by Extension Builder 2017-02-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Netthelp Template',
	'description' => 'Fluid Templates from Netthelp',
	'category' => 'distribution',
	'author' => 'Uwe Debacher',
	'author_email' => 'typo3@debacher.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.6.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-8.9.99',
			'filemetadata' => '',
			'realurl' => '',
			'version' => '',
			'gridelements' => '',
			'news' => '',
			'indexed_search' => '',
			'nettgrids' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);